###
# Get all
GET http://localhost:3333/books/nvi


###
# Get using id
GET http://localhost:3333/books/nvi?id=10e4243d-447c-4f37-a96b-cf3507006cb3



###
# Get by using query
GET http://localhost:3333/books/nvi?q=teus



###
# Get by using query
GET http://localhost:3333/books/nvi?testament=old