import './globals.css'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Toast } from '@/components/toast'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <Toast />
        {children}
      </body>
    </html>
  )
}
